"""Spec table for the data-driven Contifico tool registry (issue #4).

Auto-derived from the original hand-written tools via introspection so
the generated signatures/docstrings are byte-identical to the originals
(see tools/_registry.py for how each spec becomes a registered tool).
"""

from tools._registry import ToolSpec, register_all


SPECS = [
    ToolSpec(
        name="listar_personas",
        sig="search: str | None = None, modificados_desde_fecha: str | None = None, estado: str | None = None, fecha_inicial: str | None = None, fecha_final: str | None = None, es_proveedor: str | None = None, es_cliente: str | None = None, tipo: str | None = None, page: str | None = None, categoria_id: str | None = None",
        doc='Search and list people (customers, suppliers, employees) in Contifico.\n\n    Use this tool to find existing customers before creating a document, or to\n    get id_integracion values for other operations.\n\n    OPTIONAL PARAMETERS:\n      search (str): Search in razon_social, nombre_comercial, cedula, ruc.\n                    Example: "Juan Perez"\n      modificados_desde_fecha (str): Filter by last modification date. Format DD/MM/YYYY.\n      estado (str): Valid values: "A"=Active | "I"=Inactive\n      fecha_inicial (str): Date range start, format DD/MM/YYYY.\n      fecha_final (str): Date range end, format DD/MM/YYYY.\n      es_proveedor (str): Filter suppliers. Valid values: "1"=True | "0"=False\n      es_cliente (str): Filter customers. Valid values: "1"=True | "0"=False\n      tipo (str): Person type. Valid values: "N"=Natural | "J"=Legal entity |\n                  "I"=No ID | "P"=Plate\n      page (str): Page number for pagination. Results: 100 per page. Example: "2"\n      categoria_id (str): Filter by person category ID.\n\n    RETURNS:\n      Paginated list of person objects with: id_integracion, cedula, ruc,\n      razon_social, tipo, es_cliente, es_proveedor, email, telefonos, direccion.\n    ',
        method="GET",
        path="/api/v2/persona/",
        mode="params",
        query=(
            "search",
            "modificados_desde_fecha",
            "estado",
            "fecha_inicial",
            "fecha_final",
            "es_proveedor",
            "es_cliente",
            "tipo",
            "page",
            "categoria_id",
        ),
    ),
    ToolSpec(
        name="obtener_persona",
        sig="id_integracion: str",
        doc="Obtiene una persona por su id_integracion (varchar 16).\n\n    Devuelve todos los campos: id, ruc, cedula, razon_social, tipo,\n    es_cliente, es_proveedor, email, telefonos, direccion, etc.\n    ",
        method="GET",
        path="/api/v2/persona/{id_integracion}/",
        mode="params",
    ),
    ToolSpec(
        name="crear_persona",
        sig='pos_token: str, tipo: str, razon_social: str, es_cliente: bool, es_proveedor: bool, cedula: str = "", ruc: str | None = None, nombre_comercial: str | None = None, email: str | None = None, telefonos: str | None = None, direccion: str | None = None, placa: str | None = None, es_vendedor: bool = False, es_empleado: bool = False, es_corporativo: bool = False, es_extranjero: bool = False, aplicar_cupo: bool = False, porcentaje_descuento: float | None = None, adicionales_cliente: str | None = None, adicionales_proveedor: str | None = None, personaasociada_id: str | None = None, banco_codigo_id: str | None = None, numero_tarjeta: str | None = None, tipo_cuenta: str | None = None, origen: str | None = None',
        doc='⚠️ MUTATION — Create a person (customer, supplier, or employee) in Contifico — POST /api/v2/persona/.\n\n    REQUIRED PARAMETERS:\n      api_key (str): Contifico API key for the account.\n      pos_token (str): Contifico POS token required for write operations.\n                  "I"=No ID (requires personaasociada_id), "P"=Plate (requires placa).\n      razon_social (str): Full name or company name (max 300 chars).\n      es_cliente (bool): True if this person is a customer.\n      es_proveedor (bool): True if this person is a supplier.\n                           At least one of es_cliente/es_proveedor MUST be True.\n      cedula (str): Cedula number (10 digits). Required for all types except "I".\n                    Example: "0912345678". Use empty string "" if not applicable.\n\n    CONDITIONAL PARAMETERS:\n      ruc (str): RUC (13 digits). REQUIRED for tipo="J". Example: "0912345678001"\n      placa (str): Vehicle plate. REQUIRED for tipo="P". Example: "PBC-454"\n      personaasociada_id (str): Associated person ID. REQUIRED for tipo="I".\n\n    OPTIONAL PARAMETERS:\n      nombre_comercial (str): Trade name.\n      email (str): Email address.\n      telefonos (str): Phone numbers.\n      direccion (str): Address.\n      es_vendedor (bool, default=False): Is a salesperson.\n      es_empleado (bool, default=False): Is an employee.\n      es_corporativo (bool, default=False): Is a corporate account.\n      es_extranjero (bool, default=False): Is a foreign entity.\n      aplicar_cupo (bool, default=False): Apply credit limit.\n      porcentaje_descuento (float): Default discount percentage.\n      adicionales_cliente (str): Customer additional data (JSON string).\n      adicionales_proveedor (str): Supplier additional data (JSON string).\n      banco_codigo_id (str): Bank ID for direct debit.\n      numero_tarjeta (str): Card number for direct debit.\n      tipo_cuenta (str): Account type ("CC"=Checking, "CA"=Savings).\n      origen (str): Customer origin (for CRM segmentation).\n\n    RETURNS:\n      Dict with created person id_integracion and all fields.\n    ',
        method="POST",
        path="/api/v2/persona/",
        mode="body",
        required=(
            "tipo",
            "razon_social",
            "es_cliente",
            "es_proveedor",
            "cedula",
            "es_vendedor",
            "es_empleado",
            "es_corporativo",
            "es_extranjero",
            "aplicar_cupo",
        ),
        optional=(
            "ruc",
            "nombre_comercial",
            "email",
            "telefonos",
            "direccion",
            "placa",
            "porcentaje_descuento",
            "adicionales_cliente",
            "adicionales_proveedor",
            "personaasociada_id",
            "banco_codigo_id",
            "numero_tarjeta",
            "tipo_cuenta",
            "origen",
        ),
        pos_arg="pos_token",
        pos_in_params=True,
    ),
    ToolSpec(
        name="actualizar_persona",
        sig='pos_token: str, id_integracion: str, tipo: str, razon_social: str, es_cliente: bool, es_proveedor: bool, cedula: str = "", ruc: str | None = None, nombre_comercial: str | None = None, email: str | None = None, telefonos: str | None = None, direccion: str | None = None, placa: str | None = None, es_vendedor: bool = False, es_empleado: bool = False, es_corporativo: bool = False, es_extranjero: bool = False, aplicar_cupo: bool = False, porcentaje_descuento: float | None = None, adicionales_cliente: str | None = None, adicionales_proveedor: str | None = None, personaasociada_id: str | None = None, banco_codigo_id: str | None = None, numero_tarjeta: str | None = None, tipo_cuenta: str | None = None',
        doc="⚠️ MUTATION — Update an existing person by id_integracion in Contifico — PUT /api/v2/persona/{id}/.\n\n    REQUIRED PARAMETERS:\n      api_key (str): Contifico API key for the account.\n      pos_token (str): Contifico POS token required for write operations.\n      id_integracion (str): Person ID to update. Example: \"AB1234567890CDEF\"\n      tipo, razon_social, es_cliente, es_proveedor, cedula: Same as crear_persona.\n\n    OPTIONAL PARAMETERS:\n      Same optional fields as crear_persona (minus 'origen').\n\n    RETURNS:\n      Dict with updated person data.\n    ",
        method="PUT",
        path="/api/v2/persona/{id_integracion}/",
        mode="body",
        required=(
            "tipo",
            "razon_social",
            "es_cliente",
            "es_proveedor",
            "cedula",
            "es_vendedor",
            "es_empleado",
            "es_corporativo",
            "es_extranjero",
            "aplicar_cupo",
        ),
        optional=(
            "ruc",
            "nombre_comercial",
            "email",
            "telefonos",
            "direccion",
            "placa",
            "porcentaje_descuento",
            "adicionales_cliente",
            "adicionales_proveedor",
            "personaasociada_id",
            "banco_codigo_id",
            "numero_tarjeta",
            "tipo_cuenta",
        ),
        pos_arg="pos_token",
        pos_in_params=True,
    ),
    ToolSpec(
        name="listar_categorias",
        sig="tipo: str | None = None, search_exact: str | None = None, modificados_desde_fecha: str | None = None",
        doc='List all categories in Contifico.\n\n    OPTIONAL PARAMETERS:\n      tipo (str): Category type. Valid values: "Transaccional" | "Grupo"\n      search_exact (str): Filter by exact category name.\n      modificados_desde_fecha (str): Modified since date, format DD/MM/YYYY.\n\n    RETURNS:\n      List of category objects with: id_integracion, nombre, tipo.\n    ',
        method="GET",
        path="/api/v2/categoria/",
        mode="params",
        query=("tipo", "search_exact", "modificados_desde_fecha"),
    ),
    ToolSpec(
        name="obtener_categoria",
        sig="id_integracion: str",
        doc='Get a category by its id_integracion.\n\n    REQUIRED PARAMETERS:\n      id_integracion (str): Category ID (varchar 16). Example: "AB1234567890CDEF"\n\n    RETURNS:\n      Category object with: id_integracion, nombre, tipo.\n    ',
        method="GET",
        path="/api/v2/categoria/{id_integracion}/",
        mode="params",
    ),
    ToolSpec(
        name="crear_categoria",
        sig="nombre: str",
        doc='⚠️ MUTATION — Create a new category in Contifico — POST /api/v2/categoria/.\n\n    REQUIRED PARAMETERS:\n      nombre (str): Category name (max 300 chars). Example: "Premium Customers"\n\n    RETURNS:\n      Dict with created category id_integracion and nombre.\n    ',
        method="POST",
        path="/api/v2/categoria/",
        mode="body_literal",
        required=("nombre",),
    ),
    ToolSpec(
        name="actualizar_categoria",
        sig="id_integracion: str, nombre: str",
        doc='⚠️ MUTATION — Update a category\'s name in Contifico — PUT /api/v2/categoria/{id}/.\n\n    REQUIRED PARAMETERS:\n      id_integracion (str): Category ID (varchar 16). Example: "AB1234567890CDEF"\n      nombre (str): New category name (max 300 chars).\n\n    RETURNS:\n      Dict with updated category data.\n    ',
        method="PUT",
        path="/api/v2/categoria/{id_integracion}/",
        mode="body_literal",
        required=("nombre",),
    ),
    ToolSpec(
        name="listar_bodegas",
        sig="fecha_inicial: str | None = None, fecha_final: str | None = None",
        doc="List all warehouses in Contifico.\n\n    OPTIONAL PARAMETERS:\n      fecha_inicial (str): Modified from date, format DD/MM/YYYY.\n      fecha_final (str): Modified until date, format DD/MM/YYYY.\n\n    RETURNS:\n      List of warehouse objects with: id_integracion, nombre, codigo,\n      venta (bool), produccion (bool), compra (bool).\n    ",
        method="GET",
        path="/api/v2/bodega/",
        mode="params",
        query=("fecha_inicial", "fecha_final"),
    ),
    ToolSpec(
        name="obtener_bodega",
        sig="id_integracion: str",
        doc="Get a warehouse by its id_integracion.\n\n    REQUIRED PARAMETERS:\n      id_integracion (str): Warehouse ID (varchar 16).\n\n    RETURNS:\n      Warehouse object with: id_integracion, nombre, codigo, venta, produccion, compra.\n    ",
        method="GET",
        path="/api/v2/bodega/{id_integracion}/",
        mode="params",
    ),
    ToolSpec(
        name="listar_productos",
        sig="modificados_desde_fecha: str | None = None, fecha_inicial: str | None = None, fecha_final: str | None = None, filtro: str | None = None, page: str | None = None, estado: str | None = None, categoria_id: str | None = None",
        doc='List all products in Contifico (paginated at 100 per page).\n\n    OPTIONAL PARAMETERS:\n      modificados_desde_fecha (str): Filter by last change date, format DD/MM/YYYY.\n      fecha_inicial (str): Last modification range start, format DD/MM/YYYY.\n      fecha_final (str): Last modification range end, format DD/MM/YYYY.\n      filtro (str): Search by product name or code.\n      page (str): Page number for pagination (100 results/page). Example: "2"\n      estado (str): Valid values: "A"=Active | "I"=Inactive\n      categoria_id (str): Filter by category ID.\n\n    RETURNS:\n      Paginated list of product objects with: id_integracion, nombre, codigo,\n      pvp1, pvp2, pvp3, pvp4, estado, categoria_id.\n    ',
        method="GET",
        path="/api/v2/producto/",
        mode="params",
        query=(
            "modificados_desde_fecha",
            "fecha_inicial",
            "fecha_final",
            "filtro",
            "page",
            "estado",
            "categoria_id",
        ),
    ),
    ToolSpec(
        name="obtener_producto",
        sig="id_integracion: str",
        doc="Get the full details of a product by its id_integracion.\n\n    REQUIRED PARAMETERS:\n      id_integracion (str): Product ID (varchar 16).\n\n    RETURNS:\n      Full product object including: nombre, codigo, pvp1-4, stock,\n      categoria_id, porcentaje_iva, unidad, etc.\n    ",
        method="GET",
        path="/api/v2/producto/{id_integracion}",
        mode="params",
    ),
    ToolSpec(
        name="crear_producto",
        sig='nombre: str, codigo: str, estado: str, pvp1: float, minimo: float = 0.0, tipo: str = "PRO", tipo_producto: str = "SIM", codigo_barra: str | None = None, codigo_auxiliar: str | None = None, categoria_id: str | None = None, marca_id: str | None = None, porcentaje_iva: int | None = None, pvp2: float | None = None, pvp3: float | None = None, pvp4: float | None = None, pvp_manual: bool | None = None, cuenta_venta_id: str | None = None, cuenta_compra_id: str | None = None, cuenta_costo_id: str | None = None, costo_maximo: float | None = None, para_pos: bool | None = None, personalizado1: str | None = None, personalizado2: str | None = None, unidad: str | None = None, porcentaje_ice: float | None = None, valor_ice: float | None = None, campo_catalogo: str | None = None, maneja_nombremanual: bool | None = None, porcentaje_servicio: bool | None = None',
        doc='⚠️ MUTATION — Create a new product in Contifico — POST /api/v2/producto/.\n\n    REQUIRED PARAMETERS:\n      nombre (str): Product name (max 300 chars). Example: "Laptop Dell"\n      codigo (str): Unique product code (max 25 chars). Example: "PROD-001"\n      estado (str): Valid values: "A"=Active | "I"=Inactive\n      pvp1 (float): Primary sale price (e.g. retail). Example: 1200.00\n      minimo (float, default=0.0): Minimum stock level.\n\n    OPTIONAL PARAMETERS:\n      tipo (str, default="PRO"): "PRO"=Product | "SER"=Service\n      tipo_producto (str, default="SIM"): "SIM"=Simple (only option currently).\n      codigo_barra (str): Barcode.\n      codigo_auxiliar (str): Auxiliary code.\n      categoria_id (str): Product category ID (from listar_categorias).\n      marca_id (str): Brand ID.\n      porcentaje_iva (int): VAT percentage: 0, 12, 14, 15.\n      pvp2, pvp3, pvp4 (float): Alternative price levels.\n      pvp_manual (bool): If True, price can be overridden at POS.\n      cuenta_venta_id, cuenta_compra_id, cuenta_costo_id (str): Accounting account IDs.\n      costo_maximo (float): Maximum purchase cost.\n      para_pos (bool): Make available in POS.\n      unidad (str): Unit of measure.\n      porcentaje_ice, valor_ice (float): ICE tax fields if applicable.\n\n    RETURNS:\n      Dict with created product id_integracion and all fields.\n    ',
        method="POST",
        path="/api/v2/producto/",
        mode="body",
        required=(
            "nombre",
            "codigo",
            "estado",
            "pvp1",
            "minimo",
            "tipo",
            "tipo_producto",
        ),
        optional=(
            "codigo_barra",
            "codigo_auxiliar",
            "categoria_id",
            "marca_id",
            "porcentaje_iva",
            "pvp2",
            "pvp3",
            "pvp4",
            "pvp_manual",
            "cuenta_venta_id",
            "cuenta_compra_id",
            "cuenta_costo_id",
            "costo_maximo",
            "para_pos",
            "personalizado1",
            "personalizado2",
            "unidad",
            "porcentaje_ice",
            "valor_ice",
            "campo_catalogo",
            "maneja_nombremanual",
            "porcentaje_servicio",
        ),
    ),
    ToolSpec(
        name="actualizar_producto",
        sig='id_integracion: str, nombre: str, codigo: str, estado: str, pvp1: float, minimo: float = 0.0, tipo: str = "PRO", tipo_producto: str = "SIM", codigo_barra: str | None = None, codigo_auxiliar: str | None = None, categoria_id: str | None = None, marca_id: str | None = None, porcentaje_iva: int | None = None, pvp2: float | None = None, pvp3: float | None = None, pvp4: float | None = None, pvp_manual: bool | None = None, cuenta_venta_id: str | None = None, cuenta_compra_id: str | None = None, cuenta_costo_id: str | None = None, costo_maximo: float | None = None, para_pos: bool | None = None, personalizado1: str | None = None, personalizado2: str | None = None, unidad: str | None = None, porcentaje_ice: float | None = None, valor_ice: float | None = None, campo_catalogo: str | None = None, maneja_nombremanual: bool | None = None, porcentaje_servicio: bool | None = None',
        doc="⚠️ MUTATION — Update an existing product in Contifico — PUT /api/v2/producto/{id}.\n\n    REQUIRED PARAMETERS:\n      id_integracion (str): Product ID to update.\n      nombre, codigo, estado, pvp1 (float), minimo (float): Same as crear_producto.\n\n    OPTIONAL PARAMETERS:\n      Same optional fields as crear_producto.\n\n    RETURNS:\n      Dict with updated product data.\n    ",
        method="PUT",
        path="/api/v2/producto/{id_integracion}",
        mode="body",
        required=(
            "nombre",
            "codigo",
            "estado",
            "pvp1",
            "minimo",
            "tipo",
            "tipo_producto",
        ),
        optional=(
            "codigo_barra",
            "codigo_auxiliar",
            "categoria_id",
            "marca_id",
            "porcentaje_iva",
            "pvp2",
            "pvp3",
            "pvp4",
            "pvp_manual",
            "cuenta_venta_id",
            "cuenta_compra_id",
            "cuenta_costo_id",
            "costo_maximo",
            "para_pos",
            "personalizado1",
            "personalizado2",
            "unidad",
            "porcentaje_ice",
            "valor_ice",
            "campo_catalogo",
            "maneja_nombremanual",
            "porcentaje_servicio",
        ),
    ),
    ToolSpec(
        name="obtener_stock_producto",
        sig="id_integracion: str",
        doc="Get the stock breakdown by warehouse for a specific product.\n\n    REQUIRED PARAMETERS:\n      id_integracion (str): Product ID (varchar 16).\n\n    RETURNS:\n      List of stock entries per warehouse: bodega_nombre, bodega_id, cantidad.\n    ",
        method="GET",
        path="/api/v2/producto/{id_integracion}/stock/",
        mode="params",
    ),
    ToolSpec(
        name="listar_movimientos_inventario",
        sig="fecha_inicial: str | None = None, fecha_final: str | None = None, estado: str | None = None, tipo: str | None = None, bodega_id: str | None = None",
        doc='List inventory movements in Contifico.\n\n    OPTIONAL PARAMETERS:\n      fecha_inicial (str): Date range start, format DD/MM/YYYY.\n      fecha_final (str): Date range end, format DD/MM/YYYY.\n      estado (str): Valid values: "G"=Generated | "P"=Pending\n      tipo (str): Movement type. Valid values: "ING"=Entry | "EGR"=Exit |\n                  "TRA"=Transfer | "AJU"=Cost adjustment\n      bodega_id (str): Filter by warehouse ID.\n\n    RETURNS:\n      List of inventory movement objects with: id_integracion, tipo, fecha,\n      descripcion, bodega_id, detalles.\n    ',
        method="GET",
        path="/api/v2/movimiento-inventario/",
        mode="params",
        query=("fecha_inicial", "fecha_final", "estado", "tipo", "bodega_id"),
    ),
    ToolSpec(
        name="obtener_movimiento_inventario",
        sig="id_integracion: str",
        doc="Get an inventory movement by its id_integracion.\n\n    REQUIRED PARAMETERS:\n      id_integracion (str): Inventory movement ID (varchar 16).\n\n    RETURNS:\n      Full movement object with detalles (product_id, cantidad, precio).\n    ",
        method="GET",
        path="/api/v2/movimiento-inventario/{id_integracion}",
        mode="params",
    ),
    ToolSpec(
        name="crear_movimiento_inventario",
        sig="tipo: str, fecha: str, bodega_id: str, descripcion: str, detalles: list[dict[str, Any]], codigo: str | None = None, pos: str | None = None, bodega_destino_id: str | None = None, generar_asiento: bool = False",
        doc='⚠️ MUTATION — Create an inventory movement (entry, exit, or transfer) — POST /api/v2/movimiento-inventario/.\n\n    REQUIRED PARAMETERS:\n      tipo (str): Movement type. Valid values: "ING"=Entry | "EGR"=Exit | "TRA"=Transfer\n      fecha (str): Date in DD/MM/YYYY format. Example: "30/07/2025"\n      bodega_id (str): Source warehouse ID (varchar 16).\n      descripcion (str): Description of the movement.\n      detalles (list[dict]): List of items. Each requires:\n                             {"producto_id": "...",    # varchar 16\n                              "cantidad": 5.0,          # quantity\n                              "precio": 10.50}          # price (REQUIRED for tipo=ING)\n\n    CONDITIONAL PARAMETERS:\n      pos (str): POS token. REQUIRED for tipo="TRA".\n      bodega_destino_id (str): Destination warehouse ID. REQUIRED for tipo="TRA".\n\n    OPTIONAL PARAMETERS:\n      codigo (str): Movement reference code.\n      generar_asiento (bool, default=False): If True, auto-generates accounting entry.\n\n    RETURNS:\n      Dict with created movement id_integracion and result.\n    ',
        method="POST",
        path="/api/v2/movimiento-inventario/",
        mode="inv_create",
        required=(
            "tipo",
            "fecha",
            "bodega_id",
            "descripcion",
            "detalles",
            "generar_asiento",
        ),
        optional=("codigo", "pos", "bodega_destino_id"),
    ),
    ToolSpec(
        name="listar_documentos",
        sig="tipo_registro: str | None = None, tipo: str | None = None, fecha_modificacion: str | None = None, fecha_emision: str | None = None, fecha_vencimiento: str | None = None, fecha_creacion: str | None = None, persona_identificacion: str | None = None, page: str | None = None, result_page: int | None = None, result_size: int = 50, fecha_inicial: str | None = None, fecha_final: str | None = None, persona_id: str | None = None, bodega_id: str | None = None",
        doc='List and filter documents (invoices, credit notes, quotations, etc.) in Contifico.\n\n    OPTIONAL PARAMETERS:\n      tipo_registro (str): Party type filter. Valid values: "CLI"=Customer | "PRO"=Supplier\n      tipo (str): Document type. Valid values:\n                  "FAC"=Invoice, "LQC"=Purchase settlement, "PRE"=Pre-invoice,\n                  "NCT"=Credit note, "COT"=Quotation, "OCV"=Purchase/Sale order,\n                  "NVE"=Sales note, "DNA"=Non-authorized document.\n      fecha_modificacion (str): Modified on date, format DD/MM/YYYY.\n      fecha_emision (str): Issue date, format DD/MM/YYYY.\n      fecha_vencimiento (str): Due date, format DD/MM/YYYY.\n      fecha_creacion (str): Creation date, format DD/MM/YYYY.\n      persona_identificacion (str): Customer/supplier cedula or RUC.\n      page (str): Page number for pagination. Essential to avoid truncation. Example: "2". Default is 1.\n      result_page (int): Same as page. Backwards compatibility for older prompts.\n      result_size (int): Number of results per page. Default is 50. Max 100.\n      fecha_inicial, fecha_final (str): Issue date range, format DD/MM/YYYY.\n      persona_id (str): Person integration ID filter.\n      bodega_id (str): Warehouse filter.\n\n    RETURNS:\n      Paginated list of document objects with: id_integracion, tipo_documento,\n      documento (number), fecha_emision, total, estado, persona data.\n    ',
        method="GET",
        path="/api/v2/documento/",
        mode="documentos_list",
    ),
    ToolSpec(
        name="crear_documento",
        sig="fecha_emision: str, tipo_documento: str, tipo_registro: str, documento: str, autorizacion: str, descripcion: str, referencia: str, subtotal_0: float, subtotal_12: float, iva: float, ice: float, total: float, detalles: list[dict[str, Any]], pos: str | None = None, cliente: dict[str, Any] | None = None, persona: dict[str, Any] | None = None, vendedor: dict[str, Any] | None = None, cobros: list[dict[str, Any]] | None = None, estado: str | None = None, caja_id: str | None = None, servicio: float | None = None, adicional1: str | None = None, adicional2: str | None = None, hora_emision: str | None = None, electronico: bool | None = None, documento_relacionado_id: str | None = None, reserva_relacionada: str | None = None",
        doc='⚠️ MUTATION — Create a document (invoice, credit note, quotation, etc.) in Contifico — POST /api/v2/documento/.\n\n    REQUIRED PARAMETERS:\n      pos (str): POS API Token (CONTIFICO_POS_TOKEN). VARCHAR 36.\n      fecha_emision (str): Issue date in DD/MM/YYYY format. Example: "30/07/2025"\n      tipo_documento (str): Document type. Valid values:\n                             "FAC", "LQC", "PRE", "NCT", "COT", "OCV", "NVE", "DNA"\n      tipo_registro (str): Party type. Valid values: "CLI"=Customer | "PRO"=Supplier\n      documento (str): Document number, varchar 17. Example: "001-001-000008089"\n      autorizacion (str): SRI authorization number (varchar 49).\n      descripcion (str): Document description.\n      referencia (str): Reference data (additional identifier).\n      subtotal_0 (float): Subtotal with 0% VAT (8 int + 2 dec).\n      subtotal_12 (float): Subtotal with applicable VAT (8 int + 2 dec).\n      iva (float): Total VAT amount.\n      ice (float): ICE tax amount.\n      total (float): Document total (8 int + 2 dec).\n      detalles (list[dict]): Line items. Each requires:\n                             {"producto_id": "...",          # varchar 16\n                              "cantidad": 2.0,                # 7+6 decimals\n                              "precio": 10.50,               # 7+6 decimals\n                              "porcentaje_descuento": 0,\n                              "base_cero": 0.0,\n                              "base_gravable": 10.50,\n                              "base_no_gravable": 0.0}\n\n    OPTIONAL PARAMETERS:\n      cliente (dict): Customer person object (for tipo_registro=CLI).\n      persona (dict): Supplier person object (for tipo_registro=PRO).\n      vendedor (dict): Salesperson person object.\n      cobros (list[dict]): Collections: [{"forma_cobro": "EF", "monto": 11.50, "tipo_ping": null}]\n      estado (str): Document status: "P"=Pending, "C"=Collected.\n      caja_id (str): Cash register ID.\n      servicio (float): Service charge.\n      adicional1, adicional2 (str): Additional text fields.\n      hora_emision (str): Emission time.\n      electronico (bool): Electronic document flag.\n      documento_relacionado_id (str): Related document ID (REQUIRED for NCT type).\n      reserva_relacionada (str): ID of a related reservation (optional, for accounts\n                                  using the reservations module). Send null if not applicable.\n\n    RETURNS:\n      Dict with created document id_integracion and all fields.\n    ',
        method="POST",
        path="/api/v2/documento/",
        mode="body",
        required=(
            "fecha_emision",
            "tipo_documento",
            "tipo_registro",
            "documento",
            "autorizacion",
            "descripcion",
            "referencia",
            "subtotal_0",
            "subtotal_12",
            "iva",
            "ice",
            "total",
            "detalles",
            "reserva_relacionada",
        ),
        optional=(
            "cliente",
            "persona",
            "vendedor",
            "cobros",
            "estado",
            "caja_id",
            "servicio",
            "adicional1",
            "adicional2",
            "hora_emision",
            "electronico",
            "documento_relacionado_id",
        ),
        pos_arg="pos",
    ),
    ToolSpec(
        name="actualizar_documento",
        sig="id_integracion: str, fecha_emision: str, tipo_documento: str, tipo_registro: str, documento: str, autorizacion: str, descripcion: str, referencia: str, subtotal_0: float, subtotal_12: float, iva: float, ice: float, total: float, detalles: list[dict[str, Any]], pos: str | None = None, cliente: dict[str, Any] | None = None, persona: dict[str, Any] | None = None, vendedor: dict[str, Any] | None = None, estado: str | None = None, caja_id: str | None = None, servicio: float | None = None, adicional1: str | None = None, adicional2: str | None = None, reserva_relacionada: str | None = None",
        doc="⚠️ MUTATION — Update an existing document by id_integracion in Contifico — PUT /api/v2/documento/{id}.\n\n    Same required fields as crear_documento, but without cobros (collections).\n\n    REQUIRED PARAMETERS:\n      id_integracion (str): Document ID to update.\n      pos, fecha_emision, tipo_documento, tipo_registro, documento, autorizacion,\n      descripcion, referencia, subtotal_0, subtotal_12, iva, ice, total, detalles:\n      Same as crear_documento.\n\n    OPTIONAL PARAMETERS:\n      cliente, persona, vendedor, estado, caja_id, servicio, adicional1, adicional2.\n      reserva_relacionada (str): ID of a related reservation (optional, for accounts\n                                  using the reservations module). Send null if not applicable.\n\n    RETURNS:\n      Dict with updated document data.\n    ",
        method="PUT",
        path="/api/v2/documento/{id_integracion}",
        mode="body",
        required=(
            "fecha_emision",
            "tipo_documento",
            "tipo_registro",
            "documento",
            "autorizacion",
            "descripcion",
            "referencia",
            "subtotal_0",
            "subtotal_12",
            "iva",
            "ice",
            "total",
            "detalles",
            "reserva_relacionada",
        ),
        optional=(
            "cliente",
            "persona",
            "vendedor",
            "estado",
            "caja_id",
            "servicio",
            "adicional1",
            "adicional2",
        ),
        pos_arg="pos",
    ),
    ToolSpec(
        name="obtener_estado_documento",
        sig="id_integracion: str",
        doc='Check the SRI authorization status of an electronic document.\n\n    REQUIRED PARAMETERS:\n      id_integracion (str): Document ID (varchar 16).\n\n    RETURNS:\n      Dict with: documento_id, tipo_registro, tipo_documento, estado.\n      estado values: "Firmado" | "Enviado a SRI" | "Autorizado" | "No Firmado"\n    ',
        method="GET",
        path="/api/v2/documento/estado/{id_integracion}",
        mode="params",
    ),
    ToolSpec(
        name="listar_cobros_documento",
        sig="id_integracion: str",
        doc="List all collections (cobros) for a customer document.\n\n    REQUIRED PARAMETERS:\n      id_integracion (str): Document ID (varchar 16). Must be a customer document.\n\n    RETURNS:\n      List of collection objects with: forma_cobro, monto, tipo_ping, fecha.\n    ",
        method="GET",
        path="/api/v2/documento/{id_integracion}/cobro/",
        mode="params",
    ),
    ToolSpec(
        name="crear_cobro_documento",
        sig="id_integracion: str, forma_cobro: str, monto: float, tipo_ping: str | None = None, fecha: str | None = None, numero_cheque: str | None = None, cuenta_bancaria_id: str | None = None, numero_comprobante: str | None = None, lote: str | None = None",
        doc='⚠️ MUTATION — Register a payment collection on an existing document — POST /api/v2/documento/{id}/cobro/.\n\n    REQUIRED PARAMETERS:\n      id_integracion (str): Document ID to add the collection to (varchar 16).\n      forma_cobro (str): Payment method code. Valid values:\n                         "EF"=Cash | "CQ"=Check | "TC"=Credit card | "TRA"=Transfer\n      monto (float): Amount collected (8 int + 2 dec).\n\n    CONDITIONAL PARAMETERS:\n      tipo_ping (str): REQUIRED when forma_cobro="TC". Card processor code:\n                       "D"=Datafast | "M"=Medianet | "E"=Dataexpress |\n                       "P"=Placetopay | "A"=Alignet\n\n    OPTIONAL PARAMETERS:\n      fecha (str): Collection date, format DD/MM/YYYY.\n      numero_cheque (str): Check number (for forma_cobro=CQ, varchar 15).\n      cuenta_bancaria_id (str): Bank account ID receiving the payment (varchar 16).\n      numero_comprobante (str): Sequence/voucher number (varchar 15).\n      lote (str): Batch identifier.\n\n    RETURNS:\n      Dict with created collection id and confirmation.\n    ',
        method="POST",
        path="/api/v2/documento/{id_integracion}/cobro/",
        mode="body",
        required=("forma_cobro", "monto"),
        optional=(
            "tipo_ping",
            "fecha",
            "numero_cheque",
            "cuenta_bancaria_id",
            "numero_comprobante",
            "lote",
        ),
    ),
    ToolSpec(
        name="obtener_formas_pago_documento",
        sig="id_integracion: str",
        doc="Get the payment methods configured for a specific document.\n\n    REQUIRED PARAMETERS:\n      id_integracion (str): Document ID (varchar 16).\n\n    RETURNS:\n      List of payment method objects: forma_pago, plazo, unidad, valor.\n    ",
        method="GET",
        path="/api/v2/documento/{id_integracion}/forma_pago",
        mode="params",
    ),
    ToolSpec(
        name="listar_cuentas_bancarias",
        sig="",
        doc="List all bank accounts configured in Contifico.\n\n    RETURNS:\n      List of bank account objects with: id_integracion, nombre, numero,\n      tipo_cuenta (CC=Checking/CA=Savings), estado (A/I), saldo_inicial,\n      fecha_corte, cuenta_contable, nombre_banco.\n    ",
        method="GET",
        path="/api/v2/banco/cuenta/",
        mode="params",
    ),
    ToolSpec(
        name="obtener_cuenta_bancaria",
        sig="id_integracion: str",
        doc="Get a bank account by its id_integracion.\n\n    REQUIRED PARAMETERS:\n      id_integracion (str): Bank account ID (varchar 16).\n\n    RETURNS:\n      Bank account object with all fields.\n    ",
        method="GET",
        path="/api/v2/banco/cuenta/{id_integracion}/",
        mode="params",
    ),
    ToolSpec(
        name="listar_movimientos_bancarios",
        sig="fecha_inicial: str | None = None, fecha_final: str | None = None, pos_token: str | None = None",
        doc="Retrieve bank movements (bank statements/cartolas) from Contifico v1.\n\n    OPTIONAL PARAMETERS:\n      fecha_inicial (str): Start date, format DD/MM/YYYY.\n      fecha_final (str): End date, format DD/MM/YYYY.\n      pos_token (str): POS token. Falls back to CONTIFICO_POS_TOKEN env var if omitted.\n\n    RETURNS:\n      List of bank movement objects with: fecha, descripcion, monto, tipo (D/C).\n    ",
        method="GET",
        path="/api/v1/banco/movimiento/",
        mode="params_truthy",
    ),
    ToolSpec(
        name="obtener_parametros_empresa",
        sig="",
        doc="Retrieve company configuration parameters from Contifico.\n\n    Use this tool to check company settings, enabled features, and defaults\n    before creating documents or persons.\n\n    RETURNS:\n      List of parameter objects with: nombre, tipo, valor.\n    ",
        method="GET",
        path="/api/v2/empresa/parametros",
        mode="params",
    ),
    ToolSpec(
        name="listar_unidades",
        sig="",
        doc="List all units of measure configured in Contifico.\n\n    RETURNS:\n      List of unit objects with: id_integracion, nombre.\n    ",
        method="GET",
        path="/api/v2/unidad/",
        mode="params",
    ),
    ToolSpec(
        name="obtener_unidad",
        sig="id_integracion: str",
        doc="Get a unit of measure by its id_integracion.\n\n    REQUIRED PARAMETERS:\n      id_integracion (str): Unit ID.\n\n    RETURNS:\n      Unit object with: id_integracion, nombre.\n    ",
        method="GET",
        path="/api/v2/unidad/{id_integracion}",
        mode="params",
    ),
    ToolSpec(
        name="listar_roles_pago",
        sig="pos_token: str | None = None",
        doc="Retrieve employee payroll records (roles de pago) from Contifico v1.\n\n    OPTIONAL PARAMETERS:\n      pos_token (str): POS token. Falls back to CONTIFICO_POS_TOKEN env var if omitted.\n\n    RETURNS:\n      List of payroll objects with employee, period, net pay, and deductions.\n    ",
        method="GET",
        path="/api/v1/rrhh/rol/",
        mode="params_pos_v1",
    ),
    ToolSpec(
        name="listar_asientos",
        sig="page: str | None = None, fecha_inicial: str | None = None, fecha_final: str | None = None, centro_costo: str | None = None",
        doc='List accounting journal entries in Contifico.\n\n    OPTIONAL PARAMETERS:\n      page (str): Page number for pagination. Example: "2"\n      fecha_inicial (str): Start date, format DD/MM/YYYY.\n      fecha_final (str): End date, format DD/MM/YYYY.\n      centro_costo (str): Cost center id_integracion to filter by.\n\n    RETURNS:\n      Paginated list of journal entries with: id_integracion, fecha,\n      glosa, and detalles.\n    ',
        method="GET",
        path="/api/v2/contabilidad/asiento/",
        mode="params",
        query=("page", "fecha_inicial", "fecha_final", "centro_costo"),
    ),
    ToolSpec(
        name="obtener_asiento",
        sig="id_integracion: str",
        doc="Get a specific accounting journal entry by its id_integracion.\n\n    REQUIRED PARAMETERS:\n      id_integracion (str): Journal entry ID.\n\n    RETURNS:\n      Journal entry with: id, fecha (DD/MM/YYYY), glosa,\n      detalles (list with: cuenta_id, centro_costo_id, tipo D/H, valor).\n    ",
        method="GET",
        path="/api/v2/contabilidad/asiento/{id_integracion}",
        mode="params",
    ),
    ToolSpec(
        name="listar_cuentas_contables",
        sig="pos_token: str | None = None",
        doc="Retrieve the Chart of Accounts (Plan de Cuentas) from Contifico v1.\n\n    OPTIONAL PARAMETERS:\n      pos_token (str): POS token. Falls back to CONTIFICO_POS_TOKEN env var if omitted.\n\n    RETURNS:\n      List of accounting account objects with: id, codigo, nombre, tipo.\n    ",
        method="GET",
        path="/api/v1/contabilidad/cuenta-contable/",
        mode="params_pos_v1",
    ),
    ToolSpec(
        name="listar_centros_costo",
        sig="pos_token: str | None = None",
        doc="Retrieve cost centers from Contifico v1.\n\n    OPTIONAL PARAMETERS:\n      pos_token (str): POS token. Falls back to CONTIFICO_POS_TOKEN env var if omitted.\n\n    RETURNS:\n      List of cost center objects with: id, nombre, codigo.\n    ",
        method="GET",
        path="/api/v1/contabilidad/centro-costo/",
        mode="params_pos_v1",
    ),
    ToolSpec(
        name="crear_asiento_contable",
        sig="fecha: str, glosa: str, detalles: list[dict], pos_token: str | None = None, extra_data: dict | None = None",
        doc='⚠️ MUTATION — Create a manual accounting journal entry in Contifico v1 — POST /api/v1/contabilidad/asiento/.\n\n    REQUIRED PARAMETERS:\n      fecha (str): Entry date in DD/MM/YYYY format. Example: "30/07/2025"\n      glosa (str): Entry description/concept.\n      detalles (list[dict]): Journal entry lines. Each line requires:\n                             {"cuenta_id": "...",         # Account ID from listar_cuentas_contables\n                              "centro_costo_id": "...",   # Cost center ID (optional)\n                              "tipo": "D",                # "D"=Debit | "H"=Credit\n                              "valor": 100.00}             # Amount\n\n    OPTIONAL PARAMETERS:\n      pos_token (str): POS token. Falls back to CONTIFICO_POS_TOKEN env var if omitted.\n      extra_data (dict): Additional fields for the journal entry.\n\n    RETURNS:\n      Dict with created journal entry id_integracion.\n    ',
        method="POST",
        path="/api/v1/contabilidad/asiento/",
        mode="asiento_create",
        required=("fecha", "glosa", "detalles"),
    ),
]

# Build + register all tools on import (server.py imports this module).
TOOLS = register_all(SPECS)
